### ISSUE TITLE
Possible to seed UUID v4 random number generator?

### ISSUE THREAD

**Issue by adaszko** [rust-lang-nursery/uuid#100]
As in the title.  That would be very useful for e.g. tests where determinisms highly desired.

**Comment by alexcrichton** [comment]
The `Uuid::new_v4` constructor can't be seeded, but you can use [`impl Rand for Uuid`](https://github.com/rust-lang-nursery/uuid/blob/master/src/lib.rs#L924-L934) to specify a custom and seeded random number generator which should work for this!

**Comment by adaszko** [comment]
Wow, that hasn't occurred to me.  Thank you Alex, I will try it out 👍
