### ISSUE TITLE
0.1.18 Runtime Incompatibility

### ISSUE THREAD

**Issue by jnicholls** [rust-lang-nursery/uuid#48]
I suggest creating an explicit unit test for string formatting of the UUID's Debug and Display impl.  0.1.17 used to_simple_string() to format Display, while 0.1.18 uses to_hyphenated_string(), which is an incompatible update under a compatible semver bump (0.1.17 -> 0.1.18).  The version should have been 0.2.0 or Display should have been left as is for 0.1.18.

Thanks.

**Comment by alexcrichton** [comment]
I think this has since been dealt with, so closing.
