### ISSUE TITLE
Index out of bounds panic in UUID parser

### ISSUE THREAD

**Issue by MrAnno** [rust-lang-nursery/uuid#60]
Hello,

I managed to cause an index out of bounds panic in the `parse_str` function with the following input:

```Rust
assert_eq!(Uuid::parse_str("231231212212423424324323477343246663"), Err(InvalidLength(36)));
```

The problem here is that the `parser_str` function checks for the input length (32 or 36), but does not have any "hyphen verification" in the 36 case. Because of this, the 33rd digit will cause the panic: 

[index out of bounds: the len is 16 but the index is 16', src/lib.rs:489](https://github.com/rust-lang-nursery/uuid/blob/0.2.1/src/lib.rs#L489)
```Rust
let mut buffer = [0u8; 16];
//...
buffer[(digit / 2) as usize] = acc;
//      ^^^^^^^^^
//         16
```

I tried to implement a quick fix in two different ways, but both have drawbacks.
I can count the hyphens when the input length is 36, or I can just check for the `digit` index variable in every iteration of the parser loop.

Which would be more efficient / cleaner solution? What kind of `ParseError` should I return in this case?

**Comment by alexcrichton** [comment]
Ah I wouldn't worry too much about the performance of the parser here, I think it's not exactly heavily optimized today anyway. Also feel free to invent a new `ParseError` or slot this into an already existing varaint.
