### ISSUE TITLE
Document how to enable rustc-serializeable / serde serializable Uuids.

### ISSUE THREAD

**Issue by RandomInsano** [rust-lang-nursery/uuid#62]
I just upgraded some code from using 0.1.x to 0.2.x and I'm having some compiler trouble now as I assumed it would remain serializable by the JSON serializer. Is there work I need to do on my end, or is this on the Uuid libary's end?

Here's the error rustc is spitting out:

```
src/data/sale.rs:22:2: 22:14 error: no method named `encode` found for type `uuid::Uuid` in the current scope
src/data/sale.rs:22     pub id: Uuid,
```

And a snippet:

``` rust
    extern crate uuid;

    use self::uuid::Uuid;

    #[derive(RustcDecodable, RustcEncodable, Clone, Debug)]
    pub struct Thingamajig {
        /// Identifier for object lookup (eg database)
        pub id: Uuid,
        /// A title. This is for humans
        pub title: String,
    }
```

**Comment by alexcrichton** [comment]
Ah this is because rustc-serialize is an [optional dependency](https://github.com/rust-lang-nursery/uuid/blob/master/Cargo.toml#L16) now, if you enable that does it work?

**Comment by RandomInsano** [comment]
Ooooh! No, I had absolutely no idea. I guess this issue should morph into "document optional build dependencies"? I'm not even quite sure how to use them, but I can likely figure that out. Docs would definitely be appreciated.

**Comment by alexcrichton** [comment]
Sure! Sounds good to me. 

As a quick fix, though, this should work:

```toml
[dependencies]
uuid = { version = "0.2", features = ["rustc-serialize"] }

**Comment by RandomInsano** [comment]
That absolutely got it. Now I just need to change my code to use whatever replaced to_hyphenated_string() and I'll be in business. Thanks for the help!

**Comment by steveklabnik** [comment]
https://doc.rust-lang.org/uuid/uuid/index.html#dependencies has these docs now! I think this can be closed.

**Comment by alexcrichton** [comment]
Yay!

**Comment by RandomInsano** [comment]
All rejoice! 🎉 🍻
