### ISSUE TITLE
Generate v3 UUIDs

### ISSUE THREAD

**Issue by games647** [rust-lang-nursery/uuid#71]
I'm trying to get a v3 (md5 name based) uuid. I didn't found a something to do that. Could you add a way to do that or do I miss something?

**Comment by alexcrichton** [comment]
Currently this crate does not support v3 UUIDs, but PRs are welcome!

**Comment by rushmorem** [comment]
I think this ticket can now be closed. It [looks like v3 UUIDs are now supported](https://docs.rs/uuid/0.5.1/uuid/struct.Uuid.html#method.new_v3) in the latest release.
