### ISSUE TITLE
UUID Version 1 Implementation

### ISSUE THREAD

**Issue by angdev** [rust-lang-nursery/uuid#84]
Hi. I've just made experimental implementation of UUID Version 1, [uuid_v1_rs](https://github.com/angdev/uuid_v1_rs), due to lack of implementation of uuid v1 in this crate.

I'd like to merge this experimental implementation into this crate. Could I work for this?

**Comment by alexcrichton** [comment]
Unfortunately a v1 implementation brings in quite a few dependencies which may not be ready for in this crate, so it may be best to leave it to an external crate for now.

**Comment by angdev** [comment]
Okay. I just wish that v1 implementation could be integrated as early as possible.
