### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/uuid#86]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by alexcrichton** [comment]
Sounds good to me! On the next major version bump seems fine to drop support.

**Comment by cssivision** [comment]
is this has beed fixed? if not, i think i can fire a pr to fix this.

**Comment by KodrAus** [comment]
Dropped in #112
