### ISSUE TITLE
the trait bound ** is not satisfied problems - conflict

### ISSUE THREAD

**Issue by TrionProg** [rust-lang-nursery/uuid#87]
Hello.

I just need to get UUID from Postgres and serialize with serde. My Cargo.toml:
```
[dependencies]
serde="1.0.2"
serde_derive="*"
bincode="*"

[dependencies.uuid]
version = "0.5.0"
features = ["serde"] //allows Serialize

[dependencies.postgres]
version = "*"
features = ["with-uuid"] //allows ToSQL
```

version=0.5.0 let me to download new version of UUID and Serialize works for UUID (0.4.0 not), but postgres-shared wants 0.4.0. 

cargo tree
```
├── postgres v0.14.1
│   ├── bufstream v0.1.3
│   ├── fallible-iterator v0.1.3
│   ├── log v0.3.7 (*)
│   ├── postgres-protocol v0.2.2
│   │   ├── byteorder v1.0.0 (*)
│   │   ├── fallible-iterator v0.1.3 (*)
│   │   ├── md5 v0.3.4
│   │   └── memchr v1.0.1
│   │       └── libc v0.2.22 (*)
│   └── postgres-shared v0.2.1
│       ├── fallible-iterator v0.1.3 (*)
│       ├── hex v0.2.0
│       ├── phf v0.7.21
│       │   └── phf_shared v0.7.21
│       │       └── siphasher v0.2.2
│       ├── postgres-protocol v0.2.2 (*)
│       └── uuid v0.4.0 (*)
├── serde v1.0.2 (*)
├── serde_derive v1.0.2
│   ├── quote v0.3.15
│   ├── serde_derive_internals v0.15.0
│   │   ├── syn v0.11.11
│   │   │   ├── quote v0.3.15 (*)
│   │   │   ├── synom v0.11.3
│   │   │   │   └── unicode-xid v0.0.4
│   │   │   └── unicode-xid v0.0.4 (*)
│   │   └── synom v0.11.3 (*)
│   └── syn v0.11.11 (*)
└── uuid v0.5.0
    └── serde v1.0.2 (*)
```
So where are 2 versions of uuid and i get error
```
the trait bound `uuid::Uuid: postgres::types::FromSql` is not satisfied
```

* How rust will compile this? It think that where are 2 different separated structs UUID? How about shared methods and same memory?
* How to resolve this conflict? I edited Cargo.toml of postgres-shared in cargo cache and later cargo clean, but It uses 0.4.0 again.

**Comment by alexcrichton** [comment]
It looks like there's two versions of uuid being used? You may need to use uuid 0.4.0 temporarily instead of 0.5.0 in your application

**Comment by TrionProg** [comment]
But 0.4.0
Ok
```
[dependencies.uuid]
version = "0.4.0"
features = ["serde"]
```

```
error[E0277]: the trait bound `uuid::Uuid: serde::Serialize` is not satisfied
  --> src/db/users.rs:20:10
   |
20 | #[derive(Serialize, Deserialize, Debug)]
   |          ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `uuid::Uuid`
   |
   = note: required by `serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `uuid::Uuid: serde::Deserialize<'_>` is not satisfied
  --> src/db/users.rs:20:21
   |
20 | #[derive(Serialize, Deserialize, Debug)]
   |                     ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `uuid::Uuid`
   |
   = note: required by `serde::de::SeqAccess::next_element`

```

wonderful! And what next?

**Comment by alexcrichton** [comment]
Is that because two versions of serde are in use? Maybe 1.0 and 0.9?

**Comment by TrionProg** [comment]
I think yes
```
├── bincode v0.8.0
│   ├── byteorder v1.0.0
│   ├── num-traits v0.1.37
│   └── serde v1.0.2
├── cdrs v1.0.0-beta.9
│   ├── byteorder v0.5.3
│   ├── log v0.3.7
│   ├── lz4-compress v0.1.1
│   │   ├── byteorder v0.5.3 (*)
│   │   └── quick-error v1.2.0
│   ├── r2d2 v0.7.2
│   │   ├── antidote v1.0.0
│   │   ├── log v0.3.7 (*)
│   │   └── scheduled-thread-pool v0.1.0
│   │       └── antidote v1.0.0 (*)
│   ├── rand v0.3.15
│   │   └── libc v0.2.22
│   ├── snap v0.1.2
│   │   ├── byteorder v0.5.3 (*)
│   │   └── lazy_static v0.2.8
│   ├── time v0.1.37
│   │   └── libc v0.2.22 (*)
│   └── uuid v0.4.0
│       └── serde v0.9.15

```

```
[dependencies]
serde="1.0.2"
serde_derive="*"
bincode="*"
redis = "*"
cdrs = "1.0.0-beta.9"

[dependencies.uuid]
version = "0.4.0"
features = ["serde"]

[dependencies.postgres]
version = "*"
features = ["with-uuid"]

```

But I want use newest of packages.
repo:https://github.com/TrionProg/server_master some wast exists.

**Comment by TrionProg** [comment]
How to change version of dependence in multiple crates?
Seriously I need use 5 databases and each crate wants different versions of uuid or other common crates. Where is eternal race of versions and I am sure that authors wont change version of their crate if version of dependence have been updated. Okey I can download sources, write something like `xxx = { path = "../xxx" }`, but this is not solution and how I can publish crates in this case?. Where should be tool how to align versions of crates, or rust should use not 2 versions of UUID but merge them.

**Comment by alexcrichton** [comment]
@TrionProg you're running into a problem here where the versions are not matching up, and to get things to work you'll need them to match up. One of your dependencies is postgres, which currently uses uuid 0.4. You'll need to use uuid 0.4 in that case. The uuid 0.4 crate depends on serde 0.9, so you'll need to use serde 0.9 in that case.

**Comment by TrionProg** [comment]
It will not break if I will use newer version 99%. This is my own risk and necessity. But I need read uuid from postgres and write to cassandra/mongo etc. And what version I should use? 5 versions of uuid, serde etc? This versions will never matchup! And how I need convert uuid 0.4.0 to 0.5.0 and 0.5.2 ? And let's rememdeb the main question, this issue have been started, - It won't compile. 
Select what is better?!
1) https://github.com/rust-lang-nursery/uuid/issues/87#issue-227534773
or
2) https://github.com/rust-lang-nursery/uuid/issues/87#issuecomment-300585778
3) If I will write 0.4.0 everywhere it also wont compile. Why I need limit myself if some 1 year old library want 0.1.0 ?
Good luck!

But seriously I think rust should implement methods for UUID of 0.4.0 for postgres(it want's 0.4.0) , and 0.5.0 for 'other library'(it need 0.5.0), but if I use 0.5.0, I can not access methods of 0.4.0, but postgres may give some implementations of it's traits for 0.5.0 - To read from it and 'other library' it's own traits to write to 'other library' . Currently it does not compile. I will write 3 examples tomorrow.

**Comment by TrionProg** [comment]
Hello. Ok. let's continue.

just 2 files:
main.src
```
#[macro_use]
extern crate serde_derive;
extern crate bincode;
extern crate serde;

extern crate uuid;
extern crate redis;
extern crate cdrs;
extern crate postgres;

pub use uuid::Uuid;
use redis::Commands;
use cdrs::query::QueryBuilder;
use cdrs::types::IntoRustByName;

#[derive(Serialize, Deserialize, Debug)]
pub struct Data{
    s:String,
    pub id:Uuid,
}

fn main() {
    let client = redis::Client::open("redis://127.0.0.1/").unwrap();
    let con = client.get_connection().unwrap();

    let bin_data:Option<Vec<u8>> = con.get("45545").unwrap();

    let data=match bin_data {
        Some( bin_data ) => {
            //we use bincode to get data from redis
            let d:Data=bincode::deserialize(&bin_data).unwrap();
            d
        },
        None => {
            Data{
                s:"nothing".to_string(),
                id:Uuid::parse_str("936DA01F9ABD4d9d80C702AF85C822A8").unwrap(),//and we can parse uuid as string or generate
            }
        },
    };

    //we use postgresql
    let tls_mode = postgres::TlsMode::None;
    let postgresql_connection = postgres::Connection::connect("postgresql://postgresql_user@localhost/users",tls_mode).unwrap();

    let insert_result=postgresql_connection.execute(
        "INSERT INTO users (id) VALUES ($1)",
        &[&data.id]
    ).unwrap();


    //We use cassandra
    let cassandra_address="127.0.0.1:9042";
    let cassandra_transport = cdrs::transport::TransportTcp::new(cassandra_address).unwrap();
    let cassandra_client = cdrs::client::CDRS::new(cassandra_transport, cdrs::authenticators::NoneAuthenticator);
    let mut cassandra_session = cassandra_client.start(cdrs::compression::Compression::None).unwrap();

    let cassandra_querry=QueryBuilder::new(format!("SELECT content from files WHERE id = {};",&data.id)).finalize();
}

```

and Cargo.toml
```
[package]
name = "vpe"
version = "0.1.0"
authors = ["trionprog <trionprog@gmail.com>"]

[dependencies]
serde="0.9.15" #not 1.0.4
serde_derive="0.9.15" #not 1.0.4. This is really difficult to investigate what version of serde it wants
bincode="0.7.0" #not 0.8.0. This is really difficult to investigate what version of serde it wants
redis = "0.8.0" #it does not use uuid
cdrs = "1.0.0-rc.1" #it wants uuid 0.4.0

[dependencies.uuid]
version = "0.4.0" #of course I want use 0.5.0, but you advice.
features = ["serde"]

[dependencies.postgres]
version ="0.14.1" #this works good. because it wants 0.4.0, but sometimes it does not works because Cargo.toml of postgres-shared has >=0.4
#On my Laptop it does not works =)
#error : the trait `postgres::types::ToSql` is not implemented for `uuid::Uuid`

#try this
#path = "../rust-postgres/postgres" #rust-postgres/postgres-shared/ uses 0.5.0 for example. And it wont compile.
#I should use old verion of postgres because cdrs wants 0.4.0? I can not use new protocols, fixes of bugs etc because cdrs wants 0.4.0?
#Do you understand what you say?! Nothing personal, but seriously this is the absurd. This problem MUST be fixed. Because after 3 years
#cargo will be trash of conflicting versions of crates. I hope you understand me.
#error : the trait `postgres::types::ToSql` is not implemented for `uuid::Uuid`
#because it implements 0.5.0, not 0.4.0. see file https://github.com/sfackler/rust-postgres/blob/master/postgres-shared/src/types/uuid.rs
features = ["with-uuid"] #implement postgres::types::ToSql for uuid::Uuid
```

I think, rust should works this way:
C is common data type(uuid). It has no difference in memory structure
A is crate what wants C 0.4.0. A has method to read C from A
B is crate what wants C 0.5.0. B has method to write C to B
main.rs is code of user

* If A has code that uses C 0.4.0, it will execute code of impls for C 0.4.0.
But A can implement traits for C 0.5.0 to use C 0.5.0 in main.rs and to send to B(read C from A and send C to B)
* If B has code that uses C 0.5.0, it will execute code of impls for C 0.5.0.
But B can implement traits for C 0.4.0 to allow A use UUID from B(read C from A and send C to B)
* Main.rs manipulate with version of C, what Cargo.toml use. It may be 0.5.0 or more, but then A implements for C 0.5.0 and B implements for C 0.5.0, that is why user can read C from A and write C to B.

Curently A implements traits for C 0.4.0 and B for C 0.5.0, but C from main.rs can not be 0.4.0 and 0.5.0 at the same time, but it must be readed from A and writen to B. This is the problem.

repo:
https://github.com/TrionProg/vpe

**Comment by alexcrichton** [comment]
@TrionProg I think the problem here is that everything just needs to agree on versions of uuid, it's just not possible to have some on 0.4 and some on 0.5 when types are shared across crates. The repo you linked builds, though, is there still a problem with it?

**Comment by TrionProg** [comment]
>I think the problem here is that everything just needs to agree on versions of uuid, it's just not possible to have some on 0.4 and some on 0.5 when types are shared across crates.
And it must be fixed in the future =)

>The repo you linked builds, though, is there still a problem with it?
read Cargo.toml and above(this repo is copy of code above):
#try this
#path = "../rust-postgres/postgres"
Then it wont build because postgres wants 0.5.0. Here is some text for you =)

**Comment by alexcrichton** [comment]
@TrionProg so to be clear, I think very little of this has to do with the uuid crate itself, it's basically entirely about crate graph resolution in Cargo. Along those lines you may be interested in https://github.com/rust-lang/rfcs/pull/1977.

I also found that this diff got your project compiling: https://gist.github.com/alexcrichton/9b068da8426cd1b37008003548187c63

**Comment by TrionProg** [comment]
Yes. UUID is just example of common problematic crate.

Wow. I can not belive that It can works =) Very strange. What have you edited in Cargo.toml or you edited Cargo.lock directly? I see, where are some changes around serde, but I do not know how serde works, so I can not understand.

Hm I think, some impl may be marked by keyword extern, and then they will implement traites to all versions of C in the project, which has same memory structure. But memory structure may be changed, then we can not implement code of old version to new, then user must have way how to import both versions like `use postgres::postgres_shared::UUID as OldUUID;` and convert by himself.
do not forget that postgres has .toml like https://github.com/sfackler/rust-postgres/blob/master/Cargo.toml.

I think, you've understood me and you(rustc/cargo developers) will fix this in the future.

**Comment by alexcrichton** [comment]
I just updated the `Cargo.toml` and ran `cargo update`. Cargo's graph resolution is nondeterministic so we may have gotten two different versions (both valid, just different lock files). I believe this error is primarily related to https://github.com/rust-lang/rfcs/pull/1977, so I'm going to close in favor of that RFC
