### ISSUE TITLE
some features not found in Cargo.toml 

### ISSUE THREAD

**Issue by cssivision** [rust-lang-nursery/uuid#99]
all features `rustc-serialize serde v1 v3 v4 v5 use_std`, but only `v1 v3 v4 v5 use_std` in the Cargo.toml, lack of rustc-serialize serde(i am new to rust-lang, maybe this is a stupid question).

**Comment by alexcrichton** [comment]
Thanks for the report! This is due to the fact, however, that `rustc-serialize` and `serde` are optional dependencies, which implicitly makes them a feature.
